Issue/1165 add tearsheet group type
elyra-ai/canvas pull request #1166
Opened 2022-09-01 22:49 UTC by JesusGuerrero

Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

2022-09-06 13:41 UTC, matthoward366 commented on canvas_modules/common-canvas/src/common-properties/components/expression-toggle/expression-toggle.jsx
> +import React from "react";
Since this is only used under expression editor it would be better to move it under the expression control.

2022-09-20 15:06 UTC, matthoward366 requested changes
Code looks good overall.  Added some comments.

2022-09-20 15:06 UTC, matthoward366 commented on canvas_modules/common-canvas/src/common-properties/controls/expression/expression-toggle/expression-toggle.jsx
> +			<div className="ExpressionToggle">
Take a look at the className format used in common-properties.  Should be something like `properties-expression-toggle`

2022-09-20 15:06 UTC, matthoward366 commented on canvas_modules/common-canvas/src/common-properties/controls/expression/expression-toggle/expression-toggle.jsx
> +					iconDescription="Maximize"
I think these need to be translatable.

2022-09-20 15:06 UTC, matthoward366 commented on canvas_modules/common-canvas/src/common-properties/controls/expression/expression.jsx
> +			const isTearsheetOpen = this.props.controller.getActiveTearsheet() === this.props.control.data.tearsheet_ref;
Does this have problems if `this.props.control.data` doesn't exist or isn't that possible in this case?

2022-09-20 15:06 UTC, matthoward366 commented on canvas_modules/common-canvas/src/common-properties/panels/tearsheet/tearsheet.jsx
> +					className="tearsheet-panel"
update classname

2022-09-20 15:06 UTC, matthoward366 commented on canvas_modules/common-canvas/src/common-properties/panels/tearsheet/tearsheet.scss
> +			padding: 1.5rem 2rem;
spacing, color, etc... need to use tokens.

2022-09-20 19:21 UTC, matthoward366 commented on canvas_modules/common-canvas/locales/common-properties/locales/es.json
> +  "expression.minimize.label": "Minimize",
You don't need to update these files.  It will default back to en automatically.

2022-09-20 19:21 UTC, matthoward366 commented on canvas_modules/common-canvas/src/common-properties/controls/expression/expression-toggle/expression-toggle.jsx
> +					iconDescription={this.props.intl.formatMessage({ id: maximizeId, defaultMessage: defaultMessages[maximizeId] })}
Why do you need the default?  This should already be handled correctly in the code.

2022-09-20 19:21 UTC, matthoward366 commented on canvas_modules/common-canvas/src/common-properties/panels/tearsheet/tearsheet.scss
> +			border-bottom: 1px solid $gray-20;
This doesn't look right.  Color tokens come from here https://v10.carbondesignsystem.com/guidelines/color/usage/

2022-09-20 19:21 UTC, matthoward366 commented on canvas_modules/common-canvas/src/common-properties/panels/tearsheet/tearsheet.scss
> +			background-color: $gray-10;
same as above

2022-09-20 19:21 UTC, matthoward366 commented on canvas_modules/common-canvas/src/common-properties/panels/tearsheet/tearsheet.scss
> +				background-color: $white-0;
hmm, I don't think this is only for the expression control.  What if other controls are in the tearsheet?

2022-09-20 19:21 UTC, matthoward366 commented on canvas_modules/harness/test_resources/parameterDefs/code_paramDef.json
> +					"type": "tearsheetPanel",
fix indent

2022-09-20 19:21 UTC, matthoward366 commented on canvas_modules/harness/test_resources/parameterDefs/code_paramDef.json
> +					"id": "code-panel",
fix indent

2022-09-20 19:36 UTC, matthoward366 commented on canvas_modules/common-canvas/package.json
> +    "@elyra/pipeline-schemas": "^3.0.62",
This isn't available yet.  Are you going to create a PR to add the new panel?

2022-09-21 21:06 UTC, matthoward366 approved these changes

2022-09-21 21:06 UTC, merged

2022-09-21 21:17 UTC, JesusGuerrero commented on canvas_modules/common-canvas/__tests__/common-properties/panels/tearsheet-test.js
> +	it("should be hidden from DON on the tearsheet close button", () => {
yes