#1242 Support tooltip in password control
elyra-ai/canvas pull request #1247
Opened 2022-11-09 18:19 UTC by nabilIbm

Fixes : #1242  
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

2022-11-11 23:05 UTC, caritaou requested changes

2022-11-11 23:05 UTC, caritaou commented on canvas_modules/common-canvas/__tests__/common-properties/controls/passwordfield-test.js
> +	it("Passwordfield eyeIcon tooltip appear correctly", () => {
Can you add additional tests?
1. have the application override the labels as a single resource (test using harness)
2. use the defaults when the application didnt specify any

2022-11-11 23:05 UTC, caritaou commented on canvas_modules/common-canvas/locales/common-properties/locales/en.json
> +  "password.hidePasswordLabel.tooltip":"Custom Hide Value",
Locales under common-properties are the default if they are not overridden by the application. This should be `Show` and `Hide`

2022-11-11 23:05 UTC, caritaou commented on canvas_modules/common-canvas/__tests__/common-properties/controls/passwordfield-test.js
> +	it("Passwordfield eyeIcon tooltip appear correctly", () => {
You can take a look at this for example: https://github.com/elyra-ai/canvas/blob/main/canvas_modules/harness/src/intl/locales/en.json#L5
I added a custom label in the test harness to simulate an application specifying their own label override for the expression builder. Similarly, applications will specify their own overrides in their resources for the password icon tooltip

2022-11-13 22:43 UTC, tomlyn requested changes
Hi Nabil 
I noticed the commits for this PR include your commit for changing the toolbar size. This commit should not include commit from previous work items. Can you sort it out so this commit is not included please? Thanks.

<img width="736" alt="image" src="https://user-images.githubusercontent.com/15114439/201548396-0aa3fa8c-4056-4b5f-990d-50f32b0e351e.png">

2022-11-14 19:09 UTC, nabilIbm commented
Hi @tomlyn I'm working on creating a new PR

2022-11-14 19:19 UTC, closed without merging

2022-11-14 19:19 UTC, nabilIbm commented
CLosed.