Add Support for New Slider in Common Properties
elyra-ai/canvas pull request #1675
Opened 2024-01-24 14:34 UTC by srikant-ch5

Fixes : #1674 
 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

2024-01-24 16:49 UTC, matthoward366 requested changes
I think you'll need to add schema support in uihints for min/max.  step should already be support but it can't be part of the value.

2024-01-24 16:49 UTC, matthoward366 commented on canvas_modules/harness/test_resources/parameterDefs/slider_paramDef.json
> +    "slider": {
This can only be "slider: 10`.  We don't support an object like this.

2024-01-24 16:49 UTC, matthoward366 commented on canvas_modules/harness/test_resources/parameterDefs/slider_paramDef.json
> +      "default": {
We can't have a value like this.  Should be `default: 50` or something like that.

2024-01-24 16:49 UTC, matthoward366 commented on canvas_modules/harness/test_resources/parameterDefs/slider_paramDef.json
> +            "slider": {
This doesn't follow any of our standards.  I don't really even know how this works.

2024-01-25 10:13 UTC, srikant-ch5 commented
Hi @matthoward366 Please review the schema changes and slider component and let me know if I need to change anything.

2024-01-25 17:48 UTC, matthoward366 reviewed
Once the code changes are done we'll need unit tests.

2024-01-25 17:48 UTC, matthoward366 commented on canvas_modules/common-canvas/src/common-properties/controls/slider/slider.jsx
> +			min: props.control.min_value,
min, max, and step shouldn't be state values.  These don't change.  Does value also need to be in the state?  We should be able to get this directly from the controller/redux.

2024-01-25 17:48 UTC, matthoward366 commented on canvas_modules/common-canvas/src/common-properties/controls/slider/slider.jsx
> +					id={this.id}
Is id required?  From the docs it's not.  In that case we can remove the code for it.

2024-01-25 17:48 UTC, matthoward366 commented on canvas_modules/common-canvas/src/common-properties/controls/slider/slider.jsx
> +					min={this.state.min}
What happens in min, max, step aren't defined?  Shouldn't we default them in the code?

2024-01-25 17:48 UTC, matthoward366 commented on canvas_modules/common-canvas/src/common-properties/controls/slider/slider.jsx
> +					formatLabel={
Why does minLabel or maxLabel work?

2024-01-25 17:48 UTC, matthoward366 commented on canvas_modules/common-canvas/src/common-properties/form/ParameterInfo.js
> +				"min_value": propertyOf(uihint)("min_value"),
internally we usually use camalCase.  So minValue and maxValue.

2024-01-25 17:48 UTC, matthoward366 commented on canvas_modules/harness/test_resources/parameterDefs/slider_paramDef.json
> +	  },
Can you make sure to format the file?

2024-01-25 17:48 UTC, matthoward366 commented on canvas_modules/harness/test_resources/parameterDefs/slider_paramDef.json
> +      "type": "object",
This shouldn't be an object

2024-01-25 17:48 UTC, matthoward366 commented on canvas_modules/harness/test_resources/parameterDefs/slider_paramDef.json
> +      "type": "object",
can we also test with double values.  Something with 0 and 1 being the min/max with increments of 0.1

2024-01-25 17:48 UTC, matthoward366 commented on canvas_modules/harness/test_resources/parameterDefs/slider_paramDef.json
> +          "test": "test",
This looks wrong.  I don't think `test` is valid.

2024-01-30 11:22 UTC, srikant-ch5 commented
Hi @matthoward366 Please review these changes and also I have included test cases.

2024-01-30 22:29 UTC, matthoward366 commented on canvas_modules/common-canvas/src/common-properties/controls/slider/slider.scss
> +        background-color: #F4F4F4;
Why do you need to set this?  This should be controlled by `light` property on the control. It also needs to be set based on if it's in a tearsheet or right side flyout.

2024-01-30 22:29 UTC, matthoward366 commented on canvas_modules/common-canvas/src/common-properties/controls/slider/slider.scss
> +        min-width: 8.6rem;
Can you add a comment as to why this is needed?

2024-01-30 22:29 UTC, matthoward366 commented on canvas_modules/common-canvas/src/common-properties/controls/slider/slider.jsx
> +					formatLabel={
Can you answer this?

2024-01-30 22:29 UTC, matthoward366 commented on canvas_modules/harness/test_resources/parameterDefs/slider_paramDef.json
> +    {
Can you add more option? What happens if null or something undefined is passed in.  We usually add these into the parameterDef to validate.

2024-01-30 22:29 UTC, matthoward366 commented on canvas_modules/harness/test_resources/parameterDefs/slider_paramDef.json
> +        "test": "test",
Why is this here?  This isn't valid for the schema.

2024-01-30 22:29 UTC, matthoward366 commented on canvas_modules/harness/test_resources/parameterDefs/slider_paramDef.json
> +          "slider_error"
Can you add a test for warning?

2024-01-30 22:29 UTC, matthoward366 commented on canvas_modules/harness/test_resources/parameterDefs/slider_paramDef.json
> +          "slider"
Can you add a hidden option?

2024-02-02 14:23 UTC, matthoward366 commented on canvas_modules/common-canvas/src/common-properties/controls/slider/slider.jsx
> +					light={this.props.controller.getLight() && this.props.control.light}
Why are both of these needed?

2024-02-02 14:34 UTC, matthoward366 commented on canvas_modules/common-canvas/src/common-properties/controls/slider/slider.scss
> +		input {
Should this also have the disabled check?

2024-02-02 16:41 UTC, matthoward366 commented on canvas_modules/harness/test_resources/parameterDefs/slider_paramDef.json
> +        "min_value": null,
These need to be removed.  They aren't valid and cause schema validation errors.

2024-02-02 17:27 UTC, matthoward366 approved these changes
Looks good

2024-02-02 17:27 UTC, merged