#1635 use Carbon RadioButtonGroup in RadiosetControl instead of custom grouping code
elyra-ai/canvas pull request #1814
Opened 2024-04-02 06:14 UTC by veenas1

Fixes : #1635 
 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

2024-04-03 16:35 UTC, matthoward366 commented
I think this either needs to wait until the unit tests are updated or as part of this PR get the unit tests working with RTL.

2024-04-08 22:17 UTC, nmgokhale commented
@veenas1 This PR should be unblocked now. Jest tests are enabled in `main` branch.

2024-04-18 10:04 UTC, veenas1 commented
@matthoward366 Added a testcase, remaining tests are running fine. Could you please review.

2024-04-18 16:41 UTC, matthoward366 requested changes
Looks good.  One issue is the alignment of the tooltip is off.  This is caused by a margin added to the radio buttons.
![Screenshot 2024-04-18 at 11 39 53 AM](https://github.com/elyra-ai/canvas/assets/21126000/a1dcf260-2db9-40d6-9a2a-5019632bd743)

2024-04-18 18:04 UTC, matthoward366 commented on canvas_modules/common-canvas/src/common-properties/controls/radioset/radioset.scss
> +			margin-bottom: 3px; // align tooltip icon with the radio button
Can we use the same spacing token used for the radio buttons?

2024-04-18 21:37 UTC, matthoward366 commented
With carbon 11 it looks like we can include the tooltip in the label itself.  Can you try that?  Then we don't need this special handling.

![Screenshot 2024-04-18 at 4 35 52 PM](https://github.com/elyra-ai/canvas/assets/21126000/22bbe5f6-ce35-4724-add0-c80eecbe66ff)

2024-04-19 04:46 UTC, veenas1 commented
> With carbon 11 it looks like we can include the tooltip in the label itself. Can you try that? Then we don't need this special handling.

`labelText` is the actual label for each radio button. There is another attr `helperText`, but seems like it's for whole radio group, not for single radiobutton.
<img width="856" alt="image" src="https://github.com/elyra-ai/canvas/assets/151116685/da6df166-f544-4f4d-9ead-9d7a05300544">

2024-04-19 11:19 UTC, matthoward366 commented
>labelText is the actual label for each radio button

Right, but that label can also include the `Info` icon for each radio buttons description.  We've done that with other controls as well.

2024-04-19 19:39 UTC, matthoward366 approved these changes
Looks good

2024-04-19 21:15 UTC, merged