#278 Added landmark roles for A11y
elyra-ai/canvas pull request #279
Opened 2020-09-23 00:07 UTC by nmgokhale

To test this PR -

1. Turn on VoiceOver (command + F5)
2. Open rotor (control + option + u)
3. Use left-right arrow keys to open Landmark menu
4. Note - Toolbar won't show up in landmark menu because `role=toolbar` is not a landmark role.
![Image from iOS (4)](https://user-images.githubusercontent.com/25124000/93949648-08eb1580-fcf6-11ea-9084-8c0af9c56736.jpg)

2020-09-29 18:57 UTC, tomlyn requested changes
Should we be putting the aria label text into the translation files?

2020-09-30 19:41 UTC, nmgokhale commented
> Should we be putting the aria label text into the translation files?

`Common Canvas Header banner `and `Right Side Panel complimentary` are a part of test harness. So translations are not added for these two roles. 
Other roles are translated - 
![Screen Shot 2020-09-30 at 11 15 03 AM](https://user-images.githubusercontent.com/25124000/94731553-d35bb300-0319-11eb-83cb-d9ae51267bfd.png)

**Toolbar -** 
![canvas toolbar translation](https://user-images.githubusercontent.com/25124000/94731827-3ea58500-031a-11eb-8668-748f3f2bf1a0.jpg)

2020-09-30 21:38 UTC, tomlyn commented on canvas_modules/common-canvas/locales/palette/locales/en.json
> +  "palette.modal.label": "Modal Palette"
Can you change this to be "Dialog Palette" -- it sin't really a Modal and was badly named in the first place

2020-09-30 22:33 UTC, tomlyn approved these changes

2020-09-30 22:33 UTC, merged