#636 Added getDefaultCommentPosition method in canvas-controller
elyra-ai/canvas pull request #637
Opened 2021-04-23 22:17 UTC by nmgokhale

Fixes https://github.com/elyra-ai/canvas/issues/636
 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

2021-04-26 05:36 UTC, tomlyn requested changes

2021-04-26 05:36 UTC, tomlyn commented on canvas_modules/common-canvas/src/common-canvas/canvas-controller.js
> +				command = new CreateCommentAction(data, this.objectModel);
Could you change this so the defaultCommentPosition is passed into CreateCommentAction constructor as a parameter the set data.mousePos in the constructor please? It's just that I like to keep the case statements short and consistent with each other as much as possible.

2021-04-26 17:33 UTC, tomlyn approved these changes

2021-05-05 16:30 UTC, nmgokhale commented
This PR doesn't fix the issue - Comment added in same position when snapToGrid is enabled. Closing this PR.

2021-05-05 16:30 UTC, closed without merging