#886 Added paramDef getter/setter methods in propertiesController
elyra-ai/canvas pull request #887
Opened 2021-12-03 22:57 UTC by nmgokhale

Fixes #886 
 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

2021-12-07 23:17 UTC, nmgokhale commented
Modified `App.js`, `common-canvas-dev.js` and `common-canvas.js` files in harness to test this PR - 
![Screen Shot 2021-12-07 at 2 52 10 PM](https://user-images.githubusercontent.com/25124000/145118385-929e5ac8-e24e-4056-a63a-e7ce2392c5b1.png)
 
Used `structureTableParamDef` for testing. Logged response of `PropertiesController.getParamDef()` and `PropertiesController.getPropertyValues()` methods -
![Screen Shot 2021-12-07 at 3 15 48 PM](https://user-images.githubusercontent.com/25124000/145120659-8347b8d5-c84c-473c-aef9-83ae0035a9d3.png)

2021-12-09 17:49 UTC, matthoward366 requested changes
We'll probably want a few more tests or validation steps to make sure values are being set correctly.

2021-12-09 17:49 UTC, matthoward366 commented on canvas_modules/common-canvas/src/common-properties/properties-controller.js
> +	getParamDef(paramDef) {
I don't think this is needed.  The consuming application is passing that into us so they'll know what it is.

2021-12-09 17:49 UTC, matthoward366 commented on canvas_modules/common-canvas/src/common-properties/properties-controller.js
> +		if (formData) {
Instead of having this is 2 location we should move this under `setForm()`

2021-12-09 17:49 UTC, matthoward366 commented on canvas_modules/common-canvas/src/common-properties/properties-controller.js
> +		this.paramDef = paramDef;
Shouldn't be needed

2021-12-09 17:49 UTC, matthoward366 commented on canvas_modules/common-canvas/src/common-properties/properties-controller.js
> +		const rightFlyout = (typeof this.getPropertiesConfig().rightFlyout !== "undefined")
This might be cleaner to use `lodash get` with a default value.

2021-12-10 14:36 UTC, matthoward366 approved these changes
Looks good.

2021-12-10 14:36 UTC, merged